language: node_js
sudo: false
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
notifications:
  email:
    on_failure: never
    on_success: always
script:
  cd client
  npm install
  npm run lint-test -s